export const ARTIFACT_IPC = {
  OPEN: 'artifact:open',
  GET_META: 'artifact:getMeta',
  GET_HTML: 'artifact:getHtml',
  FETCH: 'artifact:fetch',
  READ_FILE: 'artifact:readFile',
  WRITE_FILE: 'artifact:writeFile',
  EXPORT_AS: 'artifact:exportAs',
  NOTIFY: 'artifact:notify',
  EXEC: 'artifact:exec',
  BRIDGE_CALL: 'artifact:bridgeCall',
  REQUEST_AUTH: 'artifact:requestAuth',
  GRANT_AUTH: 'artifact:grantAuth',
  LIST: 'artifact:list',
  SAVE_META: 'artifact:saveMeta',
  SAVE_HTML: 'artifact:saveHtml',
  IMPORT_FILE: 'artifact:importFile',
  READ_IMPORTED_TEXT: 'artifact:readImportedText',
  READ_IMPORTED_FILE_FACTS: 'artifact:readImportedFileFacts',
  READ_IMPORTED_IMAGE_THUMBNAIL: 'artifact:readImportedImageThumbnail',
  UPDATE_INDEX: 'artifact:updateIndex',
  WRITE_SKILL: 'artifact:writeSkill',
} as const;
