import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

describe('artifact UI metadata', () => {
  it('surfaces repository output metadata in artifact list and detail pages', () => {
    const listPage = readFileSync('src/pages/ArtifactsPage.tsx', 'utf8');
    const detailPage = readFileSync('src/pages/ArtifactDetailPage.tsx', 'utf8');
    const zh = JSON.parse(readFileSync('src/locales/zh.json', 'utf8'));
    const en = JSON.parse(readFileSync('src/locales/en.json', 'utf8'));

    expect(listPage).toContain('repositoryOutputPath');
    expect(listPage).toContain("t('artifact.repositoryOutput')");
    expect(detailPage).toContain('repositoryOutputPath');
    expect(detailPage).toContain('repositoryPreviewPath');
    expect(detailPage).toContain("t('artifact.repositoryPreview')");
    expect(listPage).toContain('htmlAudit');
    expect(listPage).toContain("t('artifact.htmlApprovalRequired')");
    expect(detailPage).toContain("t('artifact.htmlAudit')");
    expect(detailPage).toContain("t('artifact.htmlSelfContained')");
    expect(detailPage).toContain('originalFilePath');
    expect(detailPage).toContain("t('artifact.originalFilePath')");
    expect(detailPage).toContain("t('artifact.fileSize')");
    expect(detailPage).toContain('authEvents');
    expect(detailPage).toContain("t('artifact.runtimeAuth')");
    expect(detailPage).toContain('bridgeEvents');
    expect(detailPage).toContain("t('artifact.runtimeBridge')");
    expect(detailPage).toContain('reuseEvents');
    expect(detailPage).toContain("t('artifact.reuseRecords')");
    expect(detailPage).toContain('buildArtifactVersionHistory');
    expect(detailPage).toContain("t('artifact.currentVersion')");
    expect(listPage).toContain('contentSummary');
    expect(listPage).toContain('externalFormat');
    expect(detailPage).toContain('contentSummary');
    expect(detailPage).toContain("t('artifact.contentSummary')");
    expect(detailPage).toContain('externalFormat');
    expect(detailPage).toContain("t('artifact.externalFormat')");
    expect(detailPage).toContain('buildArtifactReuseReference');
    expect(detailPage).toContain("t('artifact.copyReference')");
    expect(detailPage).toContain("t('artifact.referenceCopied')");
    expect(zh.artifact.repositoryOutput).toBeTruthy();
    expect(zh.artifact.repositoryPreview).toBeTruthy();
    expect(zh.artifact.htmlAudit).toBeTruthy();
    expect(zh.artifact.htmlApprovalRequired).toBeTruthy();
    expect(zh.artifact.originalFilePath).toBeTruthy();
    expect(zh.artifact.fileSize).toBeTruthy();
    expect(zh.artifact.runtimeAuth).toBeTruthy();
    expect(zh.artifact.runtimeBridge).toBeTruthy();
    expect(zh.artifact.reuseRecords).toBeTruthy();
    expect(zh.artifact.reuseRecordCount).toBeTruthy();
    expect(zh.artifact.currentVersion).toBeTruthy();
    expect(zh.artifact.contentSummary).toBeTruthy();
    expect(zh.artifact.externalFormat).toBeTruthy();
    expect(zh.artifact.copyReference).toBeTruthy();
    expect(zh.artifact.referenceCopied).toBeTruthy();
    expect(en.artifact.repositoryOutput).toBeTruthy();
    expect(en.artifact.repositoryPreview).toBeTruthy();
    expect(en.artifact.htmlAudit).toBeTruthy();
    expect(en.artifact.htmlApprovalRequired).toBeTruthy();
    expect(en.artifact.originalFilePath).toBeTruthy();
    expect(en.artifact.fileSize).toBeTruthy();
    expect(en.artifact.runtimeAuth).toBeTruthy();
    expect(en.artifact.runtimeBridge).toBeTruthy();
    expect(en.artifact.reuseRecords).toBeTruthy();
    expect(en.artifact.reuseRecordCount).toBeTruthy();
    expect(en.artifact.currentVersion).toBeTruthy();
    expect(en.artifact.contentSummary).toBeTruthy();
    expect(en.artifact.externalFormat).toBeTruthy();
    expect(en.artifact.copyReference).toBeTruthy();
    expect(en.artifact.referenceCopied).toBeTruthy();
  });
});
