import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { buildDesktopSelfKnowledgeSkillContent } from '../lib/desktop-self-knowledge';

function readText(path: string): string {
  return readFileSync(path, 'utf8');
}

describe('product goal P0 traceability', () => {
  it('keeps screenshot-confirmed P0 scope visible in planning docs and Desktop self-knowledge', () => {
    const plans = readText('docs/PLANS.md');
    const roadmap = readText('docs/design-docs/product-goal-roadmap.md');
    const source = readText('docs/references/product-goal-conversation-2026-06-28.md');
    const skillContent = buildDesktopSelfKnowledgeSkillContent();

    const p0Scopes = [
      '开箱体验与工作系统金线',
      'Dashboard 真实推进状态',
      'Knowledge 导入/消化/健康检查',
      '事务推进闭环',
      '开始一件事闭环',
      '可复用资产一等对象',
    ];

    for (const scope of p0Scopes) {
      expect(plans).toContain(scope);
      expect(roadmap).toContain(scope);
    }

    expect(plans).toContain('截图追溯 P0 基线');
    expect(plans).toContain('不得在后续推进中降级为 P1/P2');
    expect(roadmap).toContain('不得判定 P0 已整体完成');
    expect(plans).toContain('Artifacts 页面已提供复用分类筛选');
    expect(roadmap).toContain('Artifacts 页面已提供复用分类筛选');
    expect(plans).toContain('outputs/assets/index.md');
    expect(roadmap).toContain('outputs/assets/index.md');
    expect(source).toContain('这些也是 P0 级别的内容');
    expect(source).toContain('截图追溯确认');
    expect(source).toContain('Artifacts 页面复用分类筛选');
    expect(source).toContain('Repository 可复用资产索引第一片');
    expect(source).toContain('可复用资产运行后复盘线索');
    expect(source).toContain('可复用资产运行后复盘写入入口');
    expect(source).toContain('事项尾动作复盘入口');
    expect(source).toContain('事项尾动作复盘草稿写入');
    expect(source).toContain('事项尾动作复盘确认联动');
    expect(source).toContain('事项状态尾动作处理入口');
    expect(source).toContain('事项成果尾动作保存后回写');
    expect(source).toContain('事项知识尾动作发起 ActionRun');
    expect(source).toContain('事项知识尾动作确认联动');
    expect(source).toContain('事项完成后显式归档');
    expect(source).toContain('Artifacts 发起前事项选择');
    expect(source).toContain('Artifacts 发起前即时创建事项');
    expect(source).toContain('Knowledge/Teams/RepositoryGate 发起前即时创建事项');
    expect(source).toContain('ActionRun 发起前事项面板组件化');
    expect(source).toContain('ActionRunWorkItemPicker');
    expect(source).toContain('工作事项发起计划 ActionRun');
    expect(source).toContain('事项计划审批写入与互链');
    expect(source).toContain('活跃计划发起执行 ActionRun');
    expect(source).toContain('work_matter_plan');
    expect(source).toContain('plan_execute');
    expect(source).toContain('applyWorkbenchMatterPlanApproval');
    expect(source).toContain('buildPlanExecutePrompt');
    expect(source).toContain('计划执行状态观测');
    expect(source).toContain('findLatestPlanExecutionRun');
    expect(source).toContain('计划执行成果沉淀入口');
    expect(source).toContain('计划执行成果候选提取');
    expect(source).toContain('计划执行成果候选来源扩展');
    expect(source).toContain('ActionRun 成果保存后状态刷新');
    expect(source).toContain('AI 产物创建保存表单结构化 Artifact 块');
    expect(source).toContain('AI 产物创建保存前多候选选择');
    expect(source).toContain('AI 产物创建保存前基础编辑');
    expect(source).toContain('AI 产物创建保存前 HTML 正文编辑');
    expect(source).toContain('AI 产物创建保存前文件/链接细节编辑');
    expect(source).toContain('Artifact 执行复盘 UI 入口');
    expect(source).toContain('Knowledge PDF/Office 资料导入第一片');
    expect(source).toContain('Repository 手动资产登记入口');
    expect(source).toContain('Repository 资产搜索入口');
    expect(source).toContain('Repository 资产执行记录入口');
    expect(source).toContain('desktop.repository.assets.record');
    expect(source).toContain('desktop.repository.assets.search');
    expect(source).toContain('desktop.repository.assets.execution.record');
    expect(source).toContain('runs/assets/');
    expect(source).toContain('repository:extractKnowledgeFileText');
    expect(source).toContain('artifact-execution-review-command');
    expect(source).toContain('ActionRun 成果沉淀后的 Dashboard 去重');
    expect(source).toContain('notifyActionRunsChanged');
    expect(source).toContain('artifact-ai-create-preview');
    expect(source).toContain('parseArtifactAICreatePreviews');
    expect(source).toContain('normalizeArtifactAICreatePreviewDraft');
    expect(source).toContain('shouldOfferPlanExecutionOutputPreservation');
    expect(source).toContain('extractActionRunOutputCandidates');
    expect(source).toContain('buildArtifactOutputPreservationPrompt');
    expect(source).toContain('lastAssistantResponse');
    expect(source).toContain('parseArtifactsFromText');
    expect(source).toContain('<artifact>');
    expect(source).toContain('action-run-output:<runId>');
    expect(source).toContain('artifact.source.type === "action_run"');
    expect(source).toContain('计划执行知识更新入口');
    expect(source).toContain('shouldOfferPlanExecutionKnowledgeUpdate');
    expect(source).toContain('action-run-knowledge:<runId>');
    expect(source).toContain('计划执行复盘草稿入口');
    expect(source).toContain('复盘草稿链接回来源事项');
    expect(source).toContain('计划执行知识/复盘后续入口去重');
    expect(source).toContain('计划执行复盘草稿带入相关知识更新');
    expect(source).toContain('计划执行复盘草稿带入知识更新状态摘要');
    expect(source).toContain('计划执行知识更新后的复盘入口强化');
    expect(source).toContain('计划执行知识更新后的精准复盘建议');
    expect(source).toContain('计划执行复盘草稿显式确认');
    expect(source).toContain('计划执行复盘确认后的后续动作文案');
    expect(source).toContain('计划执行知识更新状态标签');
    expect(source).toContain('计划执行复盘状态标签');
    expect(source).toContain('shouldOfferPlanExecutionReview');
    expect(source).toContain('action-run-review:<runId>');
    expect(source).toContain('relatedKnowledgeRunIds');
    expect(source).toContain('relatedKnowledgeRuns');
    expect(source).toContain('## 相关知识更新');
    expect(source).toContain('findPlanExecutionKnowledgeUpdateState');
    expect(source).toContain('getPlanExecutionKnowledgeReviewSuggestion');
    expect(source).toContain('findPlanExecutionReviewState');
    expect(source).toContain('知识无需写入');
    expect(source).toContain('复盘知识更新');
    expect(source).toContain('复盘知识写入');
    expect(source).toContain('复盘无需写入');
    expect(source).toContain('确认计划执行复盘');
    expect(source).toContain('计划执行复盘已确认');
    expect(source).toContain('复盘后沉淀成果');
    expect(source).toContain('复盘后更新知识');
    expect(source).toContain('未失败/未取消的 `knowledge_rewrite`');
    expect(source).toContain('来源事项 `## 复盘`');
    expect(source).toContain('repositoryWrite');
    expect(source).toContain('Knowledge 发起前事项选择');
    expect(source).toContain('Teams 发起前事项选择');
    expect(source).toContain('Repository 语义映射发起前事项选择');
    expect(source).toContain('ActionRun 未归属原因协议');
    expect(source).toContain('ActionRun 补归属流程');
    expect(source).toContain('archiveCompletedWorkbenchMatter');
    expect(source).toContain('workItemUnassignedReason');
    expect(source).toContain('assignAiActionRunToWorkItem');
    expect(source).toContain('confirmWorkbenchKnowledgeTailAction');
    expect(plans).toContain('发起知识更新 ActionRun');
    expect(plans).toContain('显式确认该尾动作');
    expect(plans).toContain('归档完成事项');
    expect(plans).toContain('workItemRequired: true');
    expect(plans).toContain('已有无事项运行的补归属流程已接入 ActionCenter');
    expect(plans).toContain('Artifacts 普通魔法创建发起前事项选择');
    expect(plans).toContain('Artifacts 普通魔法创建发起前即时创建事项');
    expect(plans).toContain('Knowledge/Teams/RepositoryGate 发起前即时创建事项');
    expect(plans).toContain('ActionRun 发起前事项面板组件化');
    expect(plans).toContain('ActionRunWorkItemPicker');
    expect(plans).toContain('工作事项发起计划 ActionRun');
    expect(plans).toContain('事项计划审批写入与互链');
    expect(plans).toContain('活跃计划发起执行 ActionRun');
    expect(plans).toContain('work_matter_plan');
    expect(plans).toContain('plan_execute');
    expect(plans).toContain('applyWorkbenchMatterPlanApproval');
    expect(plans).toContain('buildPlanExecutePrompt');
    expect(plans).toContain('计划执行状态观测');
    expect(plans).toContain('findLatestPlanExecutionRun');
    expect(plans).toContain('计划执行成果沉淀入口');
    expect(plans).toContain('保存后会触发 `notifyActionRunsChanged`');
    expect(plans).toContain('AI 创建保存表单已支持 `<artifact>`');
    expect(plans).toContain('AI 创建保存表单已支持多个候选产物');
    expect(plans).toContain('AI 创建保存表单已支持保存前基础编辑');
    expect(plans).toContain('AI 创建保存表单已支持保存前编辑 HTML 正文');
    expect(plans).toContain('AI 创建保存表单已支持保存前编辑文件/链接细节');
    expect(plans).toContain('Artifact 详情页已能在 `tool / script / workflow` 最近执行');
    expect(plans).toContain('复制 `desktop.artifacts.execution.review.write` JSON 命令');
    expect(plans).toContain('Artifact 详情页已能显示执行边界');
    expect(plans).toContain('Desktop 只记录审批与执行事实，不执行资产、不授予权限');
    expect(plans).toContain('`desktop.artifacts.execution.prepare` / `desktop.artifacts.execution.record`');
    expect(plans).toContain('PDF / Word / Excel / PowerPoint best-effort 文本抽取导入');
    expect(plans).toContain('计划执行成果候选提取');
    expect(plans).toContain('shouldOfferPlanExecutionOutputPreservation');
    expect(plans).toContain('extractActionRunOutputCandidates');
    expect(plans).toContain('buildArtifactOutputPreservationPrompt');
    expect(plans).toContain('lastAssistantResponse');
    expect(plans).toContain('parseArtifactsFromText');
    expect(plans).toContain('<artifact>');
    expect(plans).toContain('action-run-output:<runId>');
    expect(plans).toContain('source.type=action_run');
    expect(plans).toContain('计划执行知识更新入口');
    expect(plans).toContain('shouldOfferPlanExecutionKnowledgeUpdate');
    expect(plans).toContain('action-run-knowledge:<runId>');
    expect(plans).toContain('计划执行复盘草稿入口');
    expect(plans).toContain('把草稿链接回来源事项 `## 复盘`');
    expect(plans).toContain('计划执行知识/复盘后续入口状态刷新');
    expect(plans).toContain('计划执行复盘草稿带入相关知识更新');
    expect(plans).toContain('计划执行知识更新后的复盘入口强化');
    expect(plans).toContain('计划执行知识更新后的精准复盘建议');
    expect(plans).toContain('计划执行复盘草稿显式确认');
    expect(plans).toContain('计划执行复盘确认后的后续动作文案');
    expect(plans).toContain('计划执行知识更新状态标签');
    expect(plans).toContain('计划执行复盘状态标签');
    expect(plans).toContain('shouldOfferPlanExecutionReview');
    expect(plans).toContain('action-run-review:<runId>');
    expect(plans).toContain('relatedKnowledgeRunIds');
    expect(plans).toContain('## 相关知识更新');
    expect(plans).toContain('writePlanExecutionReviewWithKnowledge');
    expect(plans).toContain('getPlanExecutionKnowledgeReviewSuggestion');
    expect(plans).toContain('findPlanExecutionKnowledgeUpdateState');
    expect(plans).toContain('findPlanExecutionReviewState');
    expect(plans).toContain('知识无需写入');
    expect(plans).toContain('confirmReviewSourceDraft');
    expect(plans).toContain('getPlanExecutionPostReviewActionSuggestion');
    expect(plans).toContain('repositoryWrite.path/content/workItemPath');
    expect(plans).toContain('Knowledge 普通自动改写发起前事项选择');
    expect(plans).toContain('Teams 自然语言编排发起前事项选择');
    expect(plans).toContain('Repository 语义映射发起前事项选择');
    expect(roadmap).toContain('Dashboard 知识类尾动作进入 Knowledge');
    expect(roadmap).toContain('确认已处理并完成尾动作');
    expect(roadmap).toContain('归档完成事项');
    expect(roadmap).toContain('workItemUnassignedReason');
    expect(roadmap).toContain('assignAiActionRunToWorkItem');
    expect(roadmap).toContain('Artifacts 普通“AI 魔法创建”入口');
    expect(roadmap).toContain('即时创建事项');
    expect(roadmap).toContain('Knowledge、Teams、RepositoryGate');
    expect(roadmap).toContain('Knowledge 普通“消化资料 / 自动改写 / 刷新索引日志”入口');
    expect(roadmap).toContain('Teams 页面自然语言编排和快速创建 Agent 入口');
    expect(roadmap).toContain('RepositoryGate 的知识库语义映射和工作台语义映射入口');
    expect(roadmap).toContain('ActionRunWorkItemPicker');
    expect(roadmap).toContain('work_matter_plan');
    expect(roadmap).toContain('plan_execute');
    expect(roadmap).toContain('buildWorkMatterPlanPrompt');
    expect(roadmap).toContain('buildPlanExecutePrompt');
    expect(roadmap).toContain('计划执行状态观测');
    expect(roadmap).toContain('findLatestPlanExecutionRun');
    expect(roadmap).toContain('计划执行成果沉淀入口');
    expect(roadmap).toContain('保存后会触发 `notifyActionRunsChanged`');
    expect(roadmap).toContain('AI 创建保存表单已支持 `<artifact>`');
    expect(roadmap).toContain('AI 创建保存表单已支持多个候选产物');
    expect(roadmap).toContain('AI 创建保存表单已支持保存前基础编辑');
    expect(roadmap).toContain('AI 创建保存表单已支持保存前 HTML 正文编辑');
    expect(roadmap).toContain('AI 创建保存表单已支持保存前文件/链接细节编辑');
    expect(roadmap).toContain('Artifact 详情页已在执行记录下暴露“写执行复盘”入口');
    expect(roadmap).toContain('复制 `desktop.artifacts.execution.review.write` JSON 命令');
    expect(roadmap).toContain('Artifact 详情页已显示“执行边界”面板');
    expect(roadmap).toContain('`desktop.artifacts.execution.prepare` / `desktop.artifacts.execution.record`');
    expect(roadmap).toContain('不执行资产、不授予权限');
    expect(roadmap).toContain('PDF / Word / Excel / PowerPoint best-effort 文本抽取导入');
    expect(roadmap).toContain('计划执行成果候选提取');
    expect(roadmap).toContain('shouldOfferPlanExecutionOutputPreservation');
    expect(roadmap).toContain('extractActionRunOutputCandidates');
    expect(roadmap).toContain('buildArtifactOutputPreservationPrompt');
    expect(roadmap).toContain('lastAssistantResponse');
    expect(roadmap).toContain('parseArtifactsFromText');
    expect(roadmap).toContain('<artifact>');
    expect(roadmap).toContain('action-run-output:<runId>');
    expect(roadmap).toContain('source.type=action_run');
    expect(roadmap).toContain('计划执行知识更新入口');
    expect(roadmap).toContain('shouldOfferPlanExecutionKnowledgeUpdate');
    expect(roadmap).toContain('action-run-knowledge:<runId>');
    expect(roadmap).toContain('计划执行复盘草稿入口');
    expect(roadmap).toContain('草稿相对链接写回来源事项的 `## 复盘`');
    expect(roadmap).toContain('sourceExecutionId` 或 `tailActionId` 为 `action-run-review:<runId>`');
    expect(roadmap).toContain('relatedKnowledgeRunIds');
    expect(roadmap).toContain('## 相关知识更新');
    expect(roadmap).toContain('计划执行知识更新后的复盘入口强化');
    expect(roadmap).toContain('writePlanExecutionReviewWithKnowledge');
    expect(roadmap).toContain('计划执行知识更新后的精准复盘建议');
    expect(roadmap).toContain('getPlanExecutionKnowledgeReviewSuggestion');
    expect(roadmap).toContain('计划执行复盘草稿显式确认');
    expect(roadmap).toContain('确认计划执行复盘');
    expect(roadmap).toContain('计划执行复盘确认后的后续动作文案');
    expect(roadmap).toContain('Preserve Reviewed Output');
    expect(roadmap).toContain('计划执行知识更新状态标签');
    expect(roadmap).toContain('findPlanExecutionKnowledgeUpdateState');
    expect(roadmap).toContain('知识无需写入');
    expect(roadmap).toContain('计划执行复盘状态标签');
    expect(roadmap).toContain('findPlanExecutionReviewState');
    expect(roadmap).toContain('shouldOfferPlanExecutionReview');
    expect(roadmap).toContain('action-run-review:<runId>');
    expect(roadmap).toContain('applyWorkbenchMatterPlanApproval');
    expect(roadmap).toContain('repositoryWrite.path/content/workItemPath');
    expect(skillContent).toContain('Screenshot-confirmed P0 baseline');
    expect(skillContent).toContain('Do not demote these scopes to P1/P2');
    expect(skillContent).toContain('Knowledge tail actions can start a source-bound `knowledge_rewrite` ActionRun');
    expect(skillContent).toContain('check off only the matching source knowledge tail action');
    expect(skillContent).toContain('work/completed/*.md');
    expect(skillContent).toContain('workItemUnassignedReason: pending_work_item_assignment');
    expect(skillContent).toContain('ActionCenter can let the user choose an existing work item to backfill assignment');
    expect(skillContent).toContain('Standalone Artifacts AI creation can also list existing');
    expect(skillContent).toContain('can create a new `work/active` matter before starting `artifact_create`');
    expect(skillContent).toContain(
      'Knowledge, Teams, and RepositoryGate entry points can also create a new `work/active` matter',
    );
    expect(skillContent).toContain('Ordinary Knowledge rewrite entry points');
    expect(skillContent).toContain('Teams natural-language compose and quick Agent creation entry points');
    expect(skillContent).toContain('RepositoryGate semantic mapping entry points');
    expect(skillContent).toContain('ActionRunWorkItemPicker');
    expect(skillContent).toContain('shared pre-run matter picker');
    expect(skillContent).toContain('work_matter_plan');
    expect(skillContent).toContain('plan_execute');
    expect(skillContent).toContain('buildWorkMatterPlanPrompt');
    expect(skillContent).toContain('buildPlanExecutePrompt');
    expect(skillContent).toContain('findLatestPlanExecutionRun');
    expect(skillContent).toContain('latest plan execution status');
    expect(skillContent).toContain('shouldOfferPlanExecutionOutputPreservation');
    expect(skillContent).toContain('`action-run-output:<runId>`');
    expect(skillContent).toContain('Preserve Output');
    expect(skillContent).toContain('notifyActionRunsChanged');
    expect(skillContent).toContain('Dashboard and Workbench reload local ActionRun observers');
    expect(skillContent).toContain('artifact-ai-create-preview');
    expect(skillContent).toContain('rich `<artifact>` blocks');
    expect(skillContent).toContain('multiple Artifact candidates');
    expect(skillContent).toContain('selected candidate');
    expect(skillContent).toContain('edit title, type, description, tags, content summary');
    expect(skillContent).toContain('edit the HTML body for HTML candidates');
    expect(skillContent).toContain('preserve HTML body exactly');
    expect(skillContent).toContain('external format, reuse kind, URL, command, file path');
    expect(skillContent).toContain('trim file/link metadata strings');
    expect(skillContent).toContain('normalizeArtifactAICreatePreviewDraft');
    expect(skillContent).toContain('Artifact detail can show a Write execution review entry');
    expect(skillContent).toContain('copy the same JSON command');
    expect(skillContent).toContain('extractActionRunOutputCandidates');
    expect(skillContent).toContain('buildArtifactOutputPreservationPrompt');
    expect(skillContent).toContain('lastAssistantResponse');
    expect(skillContent).toContain('parseArtifactsFromText');
    expect(skillContent).toContain('<artifact>');
    expect(skillContent).toContain('explicit output candidates');
    expect(skillContent).toContain('source.type=action_run');
    expect(skillContent).toContain('shouldOfferPlanExecutionKnowledgeUpdate');
    expect(skillContent).toContain('`action-run-knowledge:<runId>`');
    expect(skillContent).toContain('Update Knowledge');
    expect(skillContent).toContain('shouldOfferPlanExecutionReview');
    expect(skillContent).toContain('`action-run-review:<runId>`');
    expect(skillContent).toContain('Write Review');
    expect(skillContent).toContain('links the draft back to the source matter `## 复盘`');
    expect(skillContent).toContain('non-failed, non-cancelled `knowledge_rewrite`');
    expect(skillContent).toContain('sourceExecutionId` or `tailActionId` equal to `action-run-review:<runId>`');
    expect(skillContent).toContain('relatedKnowledgeRunIds');
    expect(skillContent).toContain('a `## 相关知识更新` table with status and result/error summary');
    expect(skillContent).toContain('Review Knowledge Update');
    expect(skillContent).toContain('writePlanExecutionReviewWithKnowledge');
    expect(skillContent).toContain('Review Knowledge Write');
    expect(skillContent).toContain('Review No-Write Decision');
    expect(skillContent).toContain('getPlanExecutionKnowledgeReviewSuggestion');
    expect(skillContent).toContain('Confirm Plan Execution Review');
    expect(skillContent).toContain('confirmReviewSourceDraft');
    expect(skillContent).toContain('Preserve Reviewed Output');
    expect(skillContent).toContain('Update Reviewed Knowledge');
    expect(skillContent).toContain('getPlanExecutionPostReviewActionSuggestion');
    expect(skillContent).toContain('findPlanExecutionKnowledgeUpdateState');
    expect(skillContent).toContain('Knowledge No Write');
    expect(skillContent).toContain('findPlanExecutionReviewState');
    expect(skillContent).toContain('Review Draft');
    expect(skillContent).toContain('Review Confirmed');
    expect(skillContent).toContain('applyWorkbenchMatterPlanApproval');
    expect(skillContent).toContain('repositoryWrite.path/content/workItemPath');
    expect(skillContent).toContain('Artifacts UI also exposes a reuse-kind filter');
    expect(skillContent).toContain('Repository `outputs/assets/index.md`');
    expect(skillContent).toContain('desktop.repository.assets.record');
    expect(skillContent).toContain('desktop.repository.assets.search');
    expect(skillContent).toContain('desktop.repository.assets.execution.record');
    expect(skillContent).toContain('runs/assets/');
    expect(skillContent).toContain('post-run review clues');
    expect(skillContent).toContain('desktop.artifacts.execution.review.write');
  });
});
